name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flask pytest

      - name: Run tests
        run: pytest
