name: Test /time endpoint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install flask requests

      - name: Run tests
        run: |
          chmod +x ./test/unit-tests.sh
          ./test/unit-tests.sh
