name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask requests pytest

      - name: Start server
        run: |
          nohup python app.py > app.log 2>&1 &
          echo $! > app.pid
          sleep 3  # Ждём, пока сервер запустится

      - name: Run tests
        run: |
          python -m pytest test/test_time.py -v

      - name: Stop app
        run: |
          if [ -f app.pid ]; then
            kill -9 $(cat app.pid)
          fi
